srcs/requirements/main/account/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'account'

urlpatterns = [
    path('', home_view, name="home"),
    path('account/<user_id>/', account_view, name='account_view'),
    path('account/<user_id>/edit/', edit_account_view, name='edit_view'),
    path('search/', profile_search_view, name='search'),
    path('register/', signup, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('user-status/', user_status, name='user_status'),
]

srcs/requirements/main/chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('', private_chat_room_view, name='private_chat_room'),
    path('create/', create_or_return_private_chat, name='create_or_return_private_chat'),
]

srcs/requirements/main/main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from .views import *
from django.contrib.auth.views import *
from django.utils.translation import gettext as _
from pong.views import fetch_rooms
from django.views.static import serve

urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path('', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls, name="admin"),
    path('chat/', include('chat.urls', namespace='chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('pong/', include('pong.urls', namespace='pong')),
    path('tictac/', include('tictac.urls', namespace='tictac')),
    path('fetch-rooms/', fetch_rooms, name='fetch_rooms'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#     *urlpatterns,
#     prefix_default_language=False
# )

urlpatterns += [
    path('i18n/setlang/', set_language, name='set_language'),
]

urlpatterns += [
    path('change/done/', PasswordChangeDoneView.as_view(template_name='password/change_done.html'),
         name='password_change_done'),
    path('change/', PasswordChangeView.as_view(template_name='password/change.html'),
         name='password_change'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password/reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/', PasswordResetMyView.as_view(), name='password_reset'),
    path('complete/', PasswordResetCompleteView.as_view(template_name='password/reset_complete.html'),
         name='password_reset_complete'),
]

handler404 = 'main.views.handler404'

srcs/requirements/main/account/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models
from friend.models import Friend
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):

    def create_user(self, email, username, first_name, last_name, password=None):
        if not email:
            raise ValueError(_('Users must have an email address.'))
        if not username:
            raise ValueError(_('Users must have an username.'))
        if not first_name:
            raise ValueError(_('Users must have an first name.'))
        if not last_name:
            raise ValueError(_('Users must have an last name.'))
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, first_name, last_name, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


def get_upload_path(instance, field_name):
    return f'images/{instance.pk}/images.png'


def get_default_path():
    return f'images/default.svg'


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(verbose_name="username", max_length=60, unique=True)
    first_name = models.CharField(verbose_name="first_name", max_length=60, blank=False)
    last_name = models.CharField(verbose_name="last_name", max_length=60, blank=False)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    profile_image = models.ImageField(max_length=255, null=True, blank=True, default=get_default_path,
                                      upload_to=get_upload_path)
    hide_email = models.BooleanField(default=True)
    last_seen = models.DateTimeField(auto_now=True)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.username

    def get_profile_image(self):
        return str(self.profile_image)[str(self.profile_image).index(f'images/{self.pk}/'):]

    def has_perm(self, perm, obj=None):
        if self.is_active and self.is_superuser:
            return True
        return False

    def has_module_perms(self, app_label):
        return True

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        friend_object, created = Friend.objects.get_or_create(user=self)
        if created:
            friend_object.save()

srcs/requirements/main/account/views.py
import json
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.utils.translation import activate
from django.http import JsonResponse
from django.core.cache import cache
from .forms import AccountForm, UserRegisterForm, AccountUpdateForm
from .models import User
from .utils import online
from friend.models import Friend, FriendRequest
from friend.utils import get_friends_request_or_false
from friend.status import Status


def logout_view(request):
    logout(request)
    return redirect('/')


def login_view(request, *args, **kwargs):
    context = {}

    if request.POST:
        form = AccountForm(request.POST)
        if form.is_valid():
            user = authenticate(email=request.POST['email'], password=request.POST['password'])
            if user:
                login(request, user)
                destination = get_redirect_if_exists(request)
                if destination:
                    return redirect(destination)
                return redirect("/")
    else:
        form = AccountForm()
    context['login_form'] = form
    return render(request, "html/login.html", context)


def get_redirect_if_exists(request):
    redirects = None
    if request.GET:
        if request.GET['next']:
            redirects = str(request.GET['next'])
    return redirects


def signup(request, *args, **kwargs):
    user = request.user

    if user.is_authenticated:
        return redirect('/')
    context = {}
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email').lower()
            raw_password = form.cleaned_data.get('password1')
            firstname = form.cleaned_data.get('first_name')
            lastname = form.cleaned_data.get('last_name')
            account = authenticate(email=email, password=raw_password, first_name=firstname, last_name=lastname)
            login(request, account)
            destination = get_redirect_if_exists(request)
            if destination:
                return redirect(destination)
            return redirect('/')
        else:
            context['registration_form'] = form
    return render(request, 'html/register.html', context=context)


@login_required(login_url='account:login')
def account_view(request, *args, **kwargs):
    """
    logic here is kind of tricky
    is_self -> boolean
        is_friend -> boolean
            -1: no request
            0: then sent you
            1: you sent to then
    """
    context = {}
    try:
        if kwargs['user_id']:
            # always other user
            account = User.objects.get(pk=kwargs['user_id'])
    except User.DoesNotExist:
        return HttpResponse(_("User does not exist"))

    if account:
        context['id'] = account.id
        context['username'] = account.username
        context['email'] = account.email
        context['firstname'] = account.first_name
        context['lastname'] = account.last_name
        context['profile_image'] = account.profile_image.url
        context['hide_email'] = account.hide_email
    try:
        friend_list = Friend.objects.get(user=account)
    except Friend.DoesNotExist:
        friend_list = Friend(user=account)
        friend_list.save()
    if request.user.is_authenticated:
        is_blocked = Friend.objects.get(user=request.user).is_blocked(account)
        if not is_blocked and Friend.objects.get(user=account).is_blocked(request.user):
            return HttpResponseForbidden(_("You are blocked by this {} user.").format(account))
        context['is_blocked'] = is_blocked
    friends = friend_list.friends.all()
    context['friends'] = friends
    # define state template variable
    is_self = True
    is_friend = False
    user = request.user
    request_sent = Status.NO_REQUEST_SENT.value
    friend_request = None
    if user.is_authenticated and user != account:
        is_self = False
        if friends.filter(pk=user.id):
            is_friend = True
        else:
            is_friend = False
            # case 1: request has been sent from them to u: THEM_SENT
            if get_friends_request_or_false(sender=account, receiver=user):
                request_sent = Status.THEM_SENT_TO_U.value
                context['pending_friend_request_id'] = get_friends_request_or_false(sender=account, receiver=user).pk
            # case 2: request has been sent from u to them: U_SENT
            elif get_friends_request_or_false(sender=user, receiver=account):
                request_sent = Status.U_SENT_TO_THEM.value
                context['pending_friend_request_id'] = get_friends_request_or_false(sender=user, receiver=account).pk
            # case 3: no request has been sent: NO_REQUEST
            else:
                request_sent = Status.NO_REQUEST_SENT.value
    elif not user.is_authenticated:
        is_self = False
    else:
        try:
            friend_request = FriendRequest.objects.filter(receiver=user, is_active=True)
        except FriendRequest.DoesNotExist:
            pass

    context['is_self'] = is_self
    context['is_friend'] = is_friend
    context['BASE_URL'] = settings.BASE_URL
    context['request_sent'] = request_sent
    context['friend_request'] = friend_request
    context['online'] = online(account.id)
    context['last_seen'] = cache.get('seen_%s' % account.id)
    return render(request, "html/account.html", context)


@login_required(login_url='account:login')
def profile_search_view(request, *args, **kwargs):
    context = {}
    if request.method == "GET":
        try:
            query = request.GET.get("q")
            if len(query) > 0:
                result = User.objects.filter(Q(email__icontains=query) | Q(username__icontains=query))
                user = request.user
                accounts = []  # [(account1, True), (account2, False), ...]
                if user.is_authenticated:
                    # get the authenticated users friend list
                    auth_user_friend_list = Friend.objects.get(user=user)
                    for account in result:
                        accounts.append((account, auth_user_friend_list.is_mutual_friend(account)))
                    context['accounts'] = accounts
                else:
                    for account in result:
                        accounts.append((account, False))
                    context['accounts'] = accounts
        except Exception:
            HttpResponse(_("Invalid query"))
    return render(request, "html/search.html", context)


@login_required(login_url='account:login')
def edit_account_view(request, *args, **kwargs):
    try:
        account = User.objects.get(pk=kwargs['user_id'])
    except User.DoesNotExist:
        return HttpResponse(_("something went wrong"))
    if account.pk != request.user.pk:
        return HttpResponse(_("You cannot edit this account"))
    context = {}
    if request.POST:
        form = AccountUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            # account.profile_image.delete()
            form.save()
            return redirect("account:account_view", user_id=account.pk)
        else:
            form = AccountUpdateForm(
                initial={
                    "id": account.pk,
                    "username": account.username,
                    "email": account.email,
                    "first_name": account.first_name,
                    "last_name": account.last_name,
                    "profile_image": account.profile_image,
                    "hide_email": account.hide_email
                }
            )
            context['form'] = form
    else:
        form = AccountUpdateForm(
            initial=
            {
                "id": account.pk,
                "username": account.username,
                "email": account.email,
                "first_name": account.first_name,
                "last_name": account.last_name,
                "profile_image": account.profile_image,
                "hide_email": account.hide_email
            }
        )
        context['form'] = form
    context['DATA_UPLOAD_MEMORY_SIZE'] = settings.DATA_UPLOAD_MEMORY_SIZE
    return render(request, "html/edit_account.html", context)


def user_status(request):
    if request.method == 'POST':
        user_id = json.loads(request.body)['user_id']
        if user_id:
            return JsonResponse({'status': online(user_id), 'last_seen': cache.get('seen_%s' % user_id)})
        else:
            return JsonResponse({'error': 'User ID is required'}, status=400)
    else:
        return JsonResponse({'error': 'POST method is required'}, status=405)


def home_view(request):
    return render(request, 'html/home.html', {'users': User.objects.all().order_by('username')})

srcs/requirements/main/account/templates/html/edit_account.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Edit Account' %}{% endblock %}

{% block content %}
    <div id="contentPage">
        {% include 'css/style.html' %}
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="card profile-card">
                        <div class="card-body">
                            <div class="d-flex flex-column justify-content-center p-4">
                                <div class="image-container" id="id_image_container">
                                    <img class="border border-dark rounded-circle img-fluid mx-auto profile-image" id="id_profile_image_display" src="{{ form.initial.profile_image.url }}" alt="logo">
                                    <div class="middle" id="id_middle_container">
                                        <div class="text" id="id_text">{% trans 'Edit' %}</div>
                                    </div>
                                </div>
                                <form class="form-signin formElement" method="post" enctype="multipart/form-data">{% csrf_token %}
                                    <h6 class="mt-4 field-heading">{% trans 'First Name' %}</h6>
                                    <input type="text" name="first_name" id="id_first_name" minlength="3" class="form-control" placeholder="{% trans 'First Name' %}" required
                                           value="{{ form.initial.first_name }}">
                                    <h6 class="mt-4 field-heading">{% trans 'Last Name' %}</h6>
                                    <input type="text" name="last_name" id="id_lastname" minlength="3" class="form-control" placeholder="{% trans 'Last Name' %}" required
                                           value="{{ form.initial.last_name }}">
                                    <input accept="image/jpeg, image/x-png" class="d-none" type="file" name="profile_image" id="id_profile_image" onchange="readURL(this)">
                                    <h6 class="mt-4 field-heading">{% trans 'Username' %}</h6>
                                    <input type="text" name="username" id="id_input_username" class="form-control" placeholder="{% trans 'Username' %}" required
                                           value="{{ form.initial.username }}">
                                    <h6 class="mt-4 field-heading">{% trans 'Email' %}</h6>
                                    <input type="email" name="email" id="id_input_email" class="form-control" placeholder="{% trans 'Email address' %}" required autofocus value={{ form.initial.email }}>
                                    <div class="mt-4 checkbox">
                                        <label>
                                            <input type="checkbox" name="hide_email" id="id_input_hide_email"
                                                {% if form.initial.hide_email %}
                                                   checked
                                                {%endif%}>{% trans 'Hide Email' %}
                                        </label>
                                    </div>
                                    {% for field in form %}
                                        <div>
                                            {% for error in field.errors %}
                                                <p style="color: red">{{ error }}</p>
                                            {% endfor %}
                                        </div>
                                    {% endfor %}

                                    {% if form.non_field_errors %}
                                        <div style="color: red">
                                            <p>{{form.non_field_errors}}</p>
                                        </div>
                                    {% endif %}

                                    <div class="d-flex flex-column">
                                        <button class="btn btn-primary flex-grow-1" type="submit">{% trans 'Save' %}</button>
                                        <button class="mt-2 btn btn-danger" type="cancel">{% trans 'Back' %}</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% include 'js/edit_account.html' %}
    </div>
{% endblock content %}

srcs/requirements/main/account/templates/html/home.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Home' %}{% endblock %}

{% block content %}
    <div id="contentPage">
        <div class="container text-center">
            <h1 class="text-xl">{% trans 'Home' %}</h1>

            {% if request.user.is_authenticated %}
                <div style="overflow: auto; width: 400px; height: 550px;" class="border position-fixed end-0">
                    <h2>{% trans 'Users' %}</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">{% trans 'Username' %}</th>
                                <th scope="col">{% trans 'Status' %}</th>
                            </tr>
                        </thead>
                        <tbody id="user-table-body">
                            {% for user in users %}
                                {% if request.user.username != user.username %}
                                    <tr id="user-status" data-user-id="{{ user.id }}">
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <a class="btn" href="{% url 'account:account_view' user_id=user.id %}">
                                                    <img src="{{ user.profile_image.url }}" class="rounded-circle m-1" id="id_other_user_profile_image" alt="profile_logo">
                                                    {{ user.username }}
                                                </a>
                                            </div>
                                        </td>
                                        <td class="align-middle" id="status-{{ user.id }}"></td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
        {% include 'js/home.html' %}
    </div>
{% endblock %}

srcs/requirements/main/account/templates/html/login.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Login' %}{% endblock %}

{% block content %}
    <div id="contentPage">
        {% include 'css/style.html' %}
        <div class="container-fluid p-5 my-5">
            <div class="row justify-content-center">
                <div class="card card-signin">
                    <div class="card-body">
                        <form class="form-signin m-auto p-10" method="post">{% csrf_token %}
                            <input name="next" type="hidden" value="{% url 'account:home' %}">
                            <div class="d-flex flex-column pb-3">
                                <div class="img-fluid mx-auto d-block">
                                    <img width="64" height="64" class="img-fluid mx-auto d-block" src="{% static 'images/default.svg' %}" alt="logo">
                                </div>
                            </div>
                            <label for="inputEmail"></label>
                            <input autocomplete="email" type="email" name="email" id="inputEmail" class="form-control" title="{% trans 'Email address' %}" placeholder="{% trans 'Email address' %}" required autofocus>
                            <div class="password-container">
                                <input autocomplete="current-password" type="password" name="password" id="inputPassword" class="form-control my-2" title="{% trans 'Password' %}" placeholder="{% trans 'Password' %}" required>
                                <span class="eye-icon" onclick="showPass('inputPassword')">👁️</span>
                            </div>
                            {% for field in login_form %}
                                <p>
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                                </p>
                            {% endfor %}
                            {% if login_form.non_field_errors %}
                                <div style="color: red">
                                    <p>{{login_form.non_field_errors}}</p>
                                </div>
                            {% endif %}
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Login' %}</button>
                        </form>
                        <div class="d-flex flex-column my-4">
                            <a class="m-auto" href="{% url 'password_reset' %}">{% trans 'Reset password' %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

srcs/requirements/main/account/templates/html/register.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Register' %}{% endblock %}
{% block content %}

    <div id="contentPage">
        <div class="container-fluid p-5 my-5">
            <div class="row justify-content-center">
                <div class="card card-signin">
                    <div class="card-body">
                        <form class="form-signin" method="post">{% csrf_token %}
                            <div class="d-flex flex-column pb-3">
                                <img class="img-fluid mx-auto d-block" width="64" height="64" src="{% static 'images/default.svg' %}" alt="logo">
                            </div>
                            <input autocomplete="email" type="email" name="email" id="inputEmail" class="form-control my-2"
                                   title="{% trans 'Email address' %}" placeholder="{% trans 'Email address' %}" required>
                            <input autocomplete="off" type="text" name="username" id="inputUsername" class="form-control my-2"
                                   title="{% trans 'Username' %}" placeholder="{% trans 'Username' %}" required>
                            <input autocomplete="given-name" type="text" minlength="3" name="first_name" id="inputFirstName" class="form-control my-2"
                                   title="{% trans 'First Name' %}" placeholder="First Name">
                            <input autocomplete="family-name" type="text" minlength="2" name="last_name" id="inputLastName" class="form-control my-2"
                                   title="{% trans 'Last Name' %}" placeholder="Last Name">
                            <div class="password-container">
                                <input autocomplete="new-password" type="password" name="password1" id="inputPassword1" class="form-control my-2"
                                       title="{% trans 'Password' %}" placeholder="{% trans 'Password' %}" required>
                                <span class="eye-icon" onclick="showPass('inputPassword1')">👁️</span>
                            </div>
                            <div class="password-container">
                                <input autocomplete="new-password" type="password" name="password2" id="inputPassword2" class="form-control"
                                       title="{% trans 'Confirm password' %}" placeholder="{% trans 'Confirm password' %}" required>
                                <span class="eye-icon" onclick="showPass('inputPassword2')">👁️</span>
                            </div>
                            {% for field in registration_form %}
                            <p>
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            {% endfor %}
                            {% if registration_form.non_field_errors %}
                                <div style="color: red">
                                    <p>{{registration_form.non_field_errors}}</p>
                                </div>
                            {% endif %}
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Register' %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}