srcs/requirements/main/account/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'account'

urlpatterns = [
    path('', home_view, name="home"),
    path('account/<user_id>/', account_view, name='account_view'),
    path('account/<user_id>/edit/', edit_account_view, name='edit_view'),
    path('search/', profile_search_view, name='search'),
    path('register/', signup, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('user-status/', user_status, name='user_status'),
]

srcs/requirements/main/chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('', private_chat_room_view, name='private_chat_room'),
    path('create/', create_or_return_private_chat, name='create_or_return_private_chat'),
]

srcs/requirements/main/main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from .views import *
from django.contrib.auth.views import *
from django.utils.translation import gettext as _
from pong.views import fetch_rooms
from django.views.static import serve

urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path('', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls, name="admin"),
    path('chat/', include('chat.urls', namespace='chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('pong/', include('pong.urls', namespace='pong')),
    path('tictac/', include('tictac.urls', namespace='tictac')),
    path('fetch-rooms/', fetch_rooms, name='fetch_rooms'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#     *urlpatterns,
#     prefix_default_language=False
# )

urlpatterns += [
    path('i18n/setlang/', set_language, name='set_language'),
]

urlpatterns += [
    path('change/done/', PasswordChangeDoneView.as_view(template_name='password/change_done.html'),
         name='password_change_done'),
    path('change/', PasswordChangeView.as_view(template_name='password/change.html'),
         name='password_change'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password/reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/', PasswordResetMyView.as_view(), name='password_reset'),
    path('complete/', PasswordResetCompleteView.as_view(template_name='password/reset_complete.html'),
         name='password_reset_complete'),
]

handler404 = 'main.views.handler404'

srcs/requirements/main/tictac/urls.py
from django.urls import path
from .views import game_history, tictac, play, update_winner

app_name = 'tictac'

urlpatterns = [
    path('', tictac, name='tictac_create'),
    path('<room_code>', play, name='play'),
    path('history/', game_history, name='game_history'),
    path('update_winner/<room_code>', update_winner, name='update_winner'),
]

srcs/requirements/main/tictac/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone


def validate_room_code(value):
    if not value.isascii() or not value.isalnum() or len(value) >= 100:
        raise ValidationError("Invalid room code")


class TicTacToe(models.Model):
    room_code = models.CharField(max_length=100, validators=[validate_room_code])
    game_creator = models.CharField(max_length=100)
    game_opponent = models.CharField(max_length=100, blank=True, null=True)
    is_over = models.BooleanField(default=False)
    winner = models.CharField(max_length=100, blank=True, null=True)
    dated = models.DateTimeField(default=timezone.now)

    def player_count(self):
        count = 0
        if self.game_creator:
            count += 1
        if self.game_opponent:
            count += 1
        return count

srcs/requirements/main/tictac/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import TicTacToe
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.utils.translation import gettext_lazy as _
import json
import time


@login_required
def tictac(request):
    if request.method == 'POST':
        user = request.user.username
        option = request.POST.get('option')
        room_code = request.POST.get('room_code')
        if room_code is None:
            messages.error(request, _("room information not available room name {}").format(room_code))
        if option == '1':
            game = TicTacToe.objects.filter(room_code=room_code).first()
            if game is None:
                game = TicTacToe(game_creator=user, room_code=room_code)
                game.save()
                return redirect('/tictac/' + room_code)

            if game.player_count() >= 2:
                messages.error(request, _("The room is already full"))

        elif option == '2':
            game = get_object_or_404(TicTacToe, room_code=room_code)
            if game is None:
                messages.error(request, _("The room does not exist"))
                time.sleep(2)
            if game.game_creator == user:
                return redirect('/tictac/' + room_code)
            elif game.game_opponent == user and game.game_creator != user:
                return redirect('/tictac/' + room_code)
            if game.player_count() >= 2:
                messages.error(request, _("The room is already full or finish"))
                time.sleep(2)
            game.game_opponent = user
            game.save()
            return redirect('/tictac/' + room_code)
    return render(request, "html/front.html")


@login_required
def play(request, room_code):
    game = get_object_or_404(TicTacToe, room_code=room_code)

    return render(request, "html/play.html", {
        'room_code': room_code,
        'user': lambda: request.user.username if request.user.username == game.game_creator else game.game_opponent,
        'creator': game.game_creator,
        'opponent': game.game_opponent,
        'winner': game.winner
        })


def game_history(request):
    return render(request, "html/game_history.html", {
        'game_history': TicTacToe.objects.all(),
    })


@login_required
def update_winner(request, room_code):
    if request.method == 'POST':
        winner = json.loads(request.body).get('winner')
        if not winner:
            return JsonResponse({'success': False, 'error': _('Invalid request method')})
        game = get_object_or_404(TicTacToe, room_code=room_code)
        game.winner = winner
        game.save()
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'error': _('Invalid request method')})

srcs/requirements/main/tictac/templates/html/front.html
{% extends 'html/tbase.html' %}
{% load i18n %}
{% block title %}Tic Tac Toe{% endblock %}

{% block content %}
    <div id="contentPage">
        <div class="container mt-5 pt-5">
            <h2 class="text-center">{% trans 'PLAY' %} TIC TAC TOE</h2>
            <h3 class="text-center">{% trans 'Hello' %}, {{ request.user.username }}</h3>
            <div class="col-md-6 mx-auto mt-4">
                {% if messages %}
                    {% for messages in messages %}
                        <div class="alert alert-dark">
                            {{ messages }}
                        </div>
                    {% endfor %}
                {% endif %}
                <form class="formElement" method="post" action="{% url 'tictac:tictac_create' %}">{% csrf_token %}
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label>{% trans 'Choose Option' %}</label>
                            <select class="form-control" name="option">
                                <option value="1">{% trans 'Create Room Code' %}</option>
                                <option value="2">{% trans 'Have Room Code' %}</option>
                            </select>
                            <div class="col-md-12 form-group">
                                <label>{% trans 'Enter Room Code' %}</label>
                                <input type="text" name="room_code" placeholder="{% trans 'Type room code' %}" class="form-control">
                            </div>
                            <button type="submit" class="my-2 btn btn-light">{% trans 'Start Game' %}</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- Client Error MODAL -->
            <!-- Button trigger modal -->
            <button type="button" id="id_trigger_client_error_modal" class="d-none btn btn-primary" data-bs-toggle="modal" data-bs-target="#id_client_error_modal"></button>
            <!-- Modal -->
            <div class="modal fade" id="id_client_error_modal" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">{% trans 'Socket Client Error' %}</h5>
                                <button type="button" class="btn btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>

                        <div class="modal-body">
                            <p id="id_client_error_modal_body">{% trans 'Something went wrong.' %}</p>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="id_client_error_modal_close_btn">{% trans 'Close' %}</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Client Error MODAL -->
        </div>
    </div>
{% endblock %}

srcs/requirements/main/tictac/templates/html/game_history.html
{% extends 'html/tbase.html' %}
{% load i18n %}
{% block title %}{% trans 'Game History' %}{% endblock %}

{% block content %}
    <div id="contentPage">
        <div class="container mt-5 table-responsive">
            <h2 class="mb-4">{% trans 'Game History' %}</h2>
            <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">{% trans 'Player 1' %}</th>
                    <th scope="col">{% trans 'Player 2' %}</th>
                    <th scope="col">{% trans 'Winner' %}</th>
                    <th scope="col">{% trans 'Room code' %}</th>
                    <th scope="col">{% trans 'Date Played' %}</th>
                </tr>
            </thead>
            <tbody>
                    {% for game in game_history %}
                        <tr>
                            <td>{{ game.game_creator }}</td>
                            <td>{{ game.game_opponent }}</td>
                            <td>{{ game.winner }}</td>
                            <td>{{ game.room_code }}</td>
                            <td>{{ game.dated }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

srcs/requirements/main/tictac/templates/html/navbar.html
{% load i18n %}
{% load static %}
<div id="navbar_">
    <nav class="navbar navbar-expand-lg border border-top-0 rounded-xl">
        <div class="container-fluid">
            <a class="fs-3 navbar-brand" href="/">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
                    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4z"></path>
                </svg>
                {% trans 'Home' %}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="nav">
                <ul class="navbar-nav me-auto mb-lg-0">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item m-auto">
                            <a class="fs-4 btn" href="{% url 'chat:private_chat_room' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                                    <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"></path>
                                </svg>
                                {% trans 'Chat' %}
                            </a>
                        </li>
                        <li class="nav-item m-auto">
                            <a class="fs-4 btn" href="{% url 'tictac:tictac_create' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" height="18" width="18" viewBox="0 0 455.896 455.896" fill="currentColor">
                                    <path d="M432.458,330.806c8.794,0,15.926-7.132,15.926-15.926c0-8.794-7.132-15.926-15.926-15.926H331.599V155.62h100.859
                                               c8.794,0,15.926-7.132,15.926-15.926c0-8.794-7.132-15.926-15.926-15.926H331.599V22.909c0-8.796-7.132-15.926-15.926-15.926
                                               c-8.796,0-15.926,7.13-15.926,15.926v100.859H156.414V22.902c0-8.794-7.132-15.926-15.926-15.926
                                               c-8.796,0-15.926,7.132-15.926,15.926v100.867H23.695c-8.794,0-15.926,7.132-15.926,15.926c0,8.794,7.132,15.926,15.926,15.926
                                               h100.867v143.333H23.695c-8.794,0-15.926,7.132-15.926,15.926c0,8.794,7.132,15.926,15.926,15.926h100.867v100.859
                                               c0,8.796,7.13,15.926,15.926,15.926c8.794,0,15.926-7.13,15.926-15.926V330.806h143.333v100.867c0,8.794,7.13,15.926,15.926,15.926
                                               c8.794,0,15.926-7.132,15.926-15.926V330.806H432.458z M156.414,298.954V155.62h143.333v143.333H156.414z"></path>
                                    <path d="M27.652,106.497l25.235-25.241l25.235,25.241c3.11,3.11,7.184,4.666,11.26,4.666c4.075,0,8.149-1.556,11.26-4.666
                                               c6.222-6.213,6.222-16.299,0-22.519L75.408,58.735l25.233-25.243c6.222-6.221,6.222-16.306,0-22.519
                                               c-6.221-6.221-16.299-6.221-22.519,0L52.887,36.214L27.652,10.973c-6.221-6.221-16.299-6.221-22.519,0
                                               c-6.222,6.213-6.222,16.299,0,22.519l25.233,25.243L5.133,83.977c-6.222,6.221-6.222,16.307,0,22.519
                                               c3.11,3.11,7.184,4.666,11.26,4.666C20.468,111.163,24.542,109.607,27.652,106.497z"></path>
                                    <path d="M250.596,227.287l25.235-25.243c6.221-6.221,6.221-16.307,0-22.519c-6.222-6.222-16.3-6.222-22.521,0l-25.235,25.241
                                               l-25.235-25.241c-6.221-6.222-16.299-6.222-22.519,0c-6.221,6.213-6.221,16.299,0,22.519l25.235,25.243l-25.235,25.243
                                               c-6.221,6.221-6.221,16.307,0,22.519c3.11,3.11,7.186,4.666,11.26,4.666c4.075,0,8.149-1.556,11.26-4.666l25.235-25.241
                                               l25.235,25.241c3.11,3.11,7.186,4.666,11.26,4.666c4.076,0,8.149-1.556,11.261-4.666c6.221-6.213,6.221-16.299,0-22.519
                                               L250.596,227.287z"></path>
                                    <path d="M228.072,117.47c32.389,0,58.735-26.346,58.735-58.735C286.807,26.346,260.461,0,228.072,0
                                               c-32.389,0-58.735,26.346-58.735,58.735C169.337,91.123,195.684,117.47,228.072,117.47z M228.072,31.852
                                               c14.822,0,26.883,12.061,26.883,26.883c0,14.822-12.061,26.883-26.883,26.883c-14.822,0-26.883-12.061-26.883-26.883
                                               C201.189,43.913,213.25,31.852,228.072,31.852z"></path>
                                </svg>
                                Tic Tac Toe
                            </a>
                        <a class="fs-4 btn" href="{% url 'tictac:game_history' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-hourglass" viewBox="0 0 16 16">
                                <path d="M2 1.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1h-11a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1-.5-.5m2.5.5v1a3.5 3.5 0 0 0 1.989 3.158c.533.256 1.011.791 1.011 1.491v.702c0 .7-.478 1.235-1.011 1.491A3.5 3.5 0 0 0 4.5 13v1h7v-1a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351v-.702c0-.7.478-1.235 1.011-1.491A3.5 3.5 0 0 0 11.5 3V2z"></path>
                            </svg>
                            {% trans 'Game History' %}
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item p-2 m-auto">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        <form action="{% url 'set_language' %}" method="post" id="languageForm">{% csrf_token %}
                            <select class="form-select shadow-lg border form-select-sm" name="language" required>
                                <option value="" selected disabled>{% trans 'Language' %}</option>
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for lang in languages %}
                                    <option class="" value="{{ lang.code }}" {% if lang.code == LANGUAGE_CODE %}selected{% endif %}>
                                        {% trans lang.name %} ({{ lang.code }})
                                    </option>
                                {% endfor %}
                            </select>
                        </form>
                    </li>
                    {% if request.user.is_authenticated %}
                        <!-- PROFILE -->
                        <li class="navbar-item p-2 m-auto">
                            <form class="search-bar justify-content-start" onsubmit="return executeQuery();">
                                <label><input type="text" class="shadow-lg form-control" name="q" id="id_q_small" placeholder="{% trans 'Search' %}"></label>
                            </form>
                        </li>
                        <li class="nav-item p-2 m-auto">
                            <div class="btn-group dropstart">
                                <img class="account-image m-auto rounded-circle d-block dropdown-toggle" id="profile_links" data-bs-toggle="dropdown"
                                  alt="logo" width="40" height="40" src="{{ request.user.profile_image.url }}"
                                 aria-labelledby="profile_links" aria-haspopup="true" aria-expanded="false">
                                <div class="dropdown-menu">
                                    <a class="fs-4 dropdown-item" href="{% url 'account:account_view' user_id=request.user.pk %}">{% trans 'Account' %}</a>
                                    <a class="fs-4 dropdown-item" href="{% url 'account:logout' %}">{% trans 'Logout' %}</a>
                                </div>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item p-2 m-auto">
                            <a class="fs-5 btn btn-bd-primary" href="{% url 'account:login' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-door-open" viewBox="0 0 16 16">
                                    <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1"></path>
                                    <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117M11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5M4 1.934V15h6V1.077z"></path>
                                </svg>
                                {% trans 'Login' %}
                            </a>
                        </li>
                        <li class="nav-item p-2 m-auto">
                            <a class="fs-5 btn btn-bd-primary" href="{% url 'account:register' %}">{% trans 'Sign Up' %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <script>
        function executeQuery(event) {
            event.preventDefault();
            const searchData = document.getElementById("id_q_small").value;
            fetch("{% url 'account:search' %}?q=" + searchData)
                .then(response => {
                    return response.text();
                })
                .then(data => {
                    document.body.innerHTML = data;
                })
        }
</script>
</div>

srcs/requirements/main/tictac/templates/html/play.html
{% extends 'html/tbase.html' %}
{% load i18n %}
{% block title %}Tic Tac Toe{% endblock %}

{% block content %}
    <div id="contentPage">
        <div class="container mt-3 pt-5">
            <h2 class="text-center">{% trans 'PLAY' %} TIC TAC TOE</h2>
            <h3 class="text-center">{% trans 'Hello' %}, {{ user }}</h3>
        </div>
        <div class="full-page" id="full-page">
            <div class="container mt-5">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6">
                        <div class="game" id="game-container" style="display: none;">
                            <div class="scoreboard">
                                <div id="player" class="text-black"></div>
                            </div>
                            <div class="boardcontainer">
                                <div class="board">
                                    <div data-cell-index="0" class="space text-black"></div>
                                    <div data-cell-index="1" class="space text-black"></div>
                                    <div data-cell-index="2" class="space text-black"></div>

                                    <div data-cell-index="3" class="space text-black"></div>
                                    <div data-cell-index="4" class="space text-black"></div>
                                    <div data-cell-index="5" class="space text-black"></div>

                                    <div data-cell-index="6" class="space text-black"></div>
                                    <div data-cell-index="7" class="space text-black"></div>
                                    <div data-cell-index="8" class="space text-black"></div>
                                    </div>
                                </div>
                        </div>
                        <div id="containers"></div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'js/play.html' %}
    </div>
{% endblock %}

srcs/requirements/main/tictac/templates/html/tbase.html
<!DOCTYPE html>
{% load static %}
<html lang="{% if request.session.lang %}{{ request.session.lang }}{% else %}en{% endif %}" data-bs-theme="auto">
	<head>
		{% include 'part/head.html' %}
        <title>{% block title %}{% endblock %}</title>
	</head>
	<body>
		{% include 'part/color-mode.html' %}
		{% include 'html/navbar.html' %}

        {% block content %}{% endblock %}
        <script src="{% static 'js/main.html' %}"></script>
	</body>
</html>