srcs/requirements/main/chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('', private_chat_room_view, name='private_chat_room'),
    path('create/', create_or_return_private_chat, name='create_or_return_private_chat'),
]

srcs/requirements/main/main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from .views import *
from django.contrib.auth.views import *
from django.utils.translation import gettext as _
from pong.views import fetch_rooms
from django.views.static import serve

urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path('', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls, name="admin"),
    path('chat/', include('chat.urls', namespace='chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('pong/', include('pong.urls', namespace='pong')),
    path('tictac/', include('tictac.urls', namespace='tictac')),
    path('fetch-rooms/', fetch_rooms, name='fetch_rooms'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#     *urlpatterns,
#     prefix_default_language=False
# )

urlpatterns += [
    path('i18n/setlang/', set_language, name='set_language'),
]

urlpatterns += [
    path('change/done/', PasswordChangeDoneView.as_view(template_name='password/change_done.html'),
         name='password_change_done'),
    path('change/', PasswordChangeView.as_view(template_name='password/change.html'),
         name='password_change'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password/reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/', PasswordResetMyView.as_view(), name='password_reset'),
    path('complete/', PasswordResetCompleteView.as_view(template_name='password/reset_complete.html'),
         name='password_reset_complete'),
]

handler404 = 'main.views.handler404'

srcs/requirements/main/pong/urls.py
from . import views
from django.utils.translation import gettext as _
from django.urls import path

app_name = 'pong'

urlpatterns = [
	path('', views.home, name="home"),
	path("game_history/", views.game_history, name='history'),
	path('tournament/', views.tournament, name='tournament'),
	path('update_winner/<room_name>', views.update, name='update'),
	path("<room_name>/", views.room, name='room'),
	path('ai', views.ai, name='ai'),
	path('offline', views.offline, name='offline'),
]

srcs/requirements/main/pong/models.py
from django.db import models

class Room(models.Model):
    room_name = models.CharField(max_length=255, unique=True)
    game_creator = models.CharField(max_length=100)
    game_opponent = models.CharField(max_length=100, blank=True, null=True)
    is_over = models.BooleanField(default=False)
    winner = models.CharField(max_length=100, blank=True, null=True)

    def player_count(self):
        count = 0
        if self.game_creator:
            count += 1
        if self.game_opponent:
            count += 1
        return count

    def __str__(self):
        return self.room_name

srcs/requirements/main/pong/views.py
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Room
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
import json
import time


@login_required
def home(request):
    rooms = Room.objects.all()
    if request.method == 'POST':
        user = request.user.username
        option = request.POST.getlist('option')[0]
        room_name = request.POST.getlist('oda_ismi')[0]
        if room_name is None:
            messages.error(request, _("room information not available room name {}").format(room_name))
            time.sleep(2)
        if option == '1':
            game = Room.objects.filter(room_name=room_name).first()
            if game is None:
                game = Room(game_creator=user, room_name=room_name)
                game.save()
                return redirect('/pong/' + room_name)

            if game.player_count() >= 2:
                messages.error(request, _("The room is already full or finish"))
                time.sleep(2)

        if option == '2':
            game = get_object_or_404(Room, room_name=room_name)
            if game is None:
                messages.error(request, _("The room does not exist"))
                time.sleep(2)
            if game.game_creator == user:
                return redirect('/pong/' + room_name)
            elif game.game_opponent == user and game.game_creator != user:
                return redirect('/pong/' + room_name)
            if game.player_count() >= 2:
                messages.error(request, _("The room is already full or finish"))
                time.sleep(2)
            game.game_opponent = user
            game.save()
            return redirect('/pong/' + room_name)
    return render(request, 'html/game_home.html', {'rooms': rooms})


@login_required
def room(request, room_name):
    game = get_object_or_404(Room, room_name=room_name)

    return render(request, "html/oda.html", {
        'room_name': room_name,
        'user': lambda: request.user.username if request.user.username == game.game_creator else game.game_opponent,
        'creator': game.game_creator,
        'opponent': game.game_opponent,
        'winner': game.winner,
        'game_over': game.is_over
        })


@login_required
def game_history(request):
    return render(request, "html/history.html", {'game_history': Room.objects.all()})


@login_required
def update(request, room_name):
    if request.method == 'POST':
        winner = json.loads(request.body).get('winner')
        if not winner:
            return JsonResponse({'success': False, 'error': _('Invalid request method')})
        game = get_object_or_404(Room, room_name=room_name)
        game.winner = winner
        game.save()
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'error': _('Invalid request method')})


@login_required()
def fetch_rooms(request):
    rooms = Room.objects.all()
    rooms_list = [
        {
            'name': room.room_name,
            'size': room.player_count(),
            'creator': room.game_creator,
            'opponent': room.game_opponent,
            'is_over': room.is_over
        }
        for room in rooms
    ]
    return JsonResponse({'rooms': rooms_list})


def tournament(request):
    return render(request, 'html/turnuva.html')


def ai(request):
    return render(request, 'html/ai.html')


def offline(request):
    return render(request, 'html/offline.html')

srcs/requirements/main/pong/templates/js/ai.html
{% load i18n %}
<script>
    // Select the canvas element
    const canvas = document.getElementById('pong');
    const context = canvas.getContext('2d');

    // Playground sizes
    const fieldWidth = canvas.width;
    const fieldHeight = canvas.height;


    // Player and AI racket
    const paddleWidth = 10;
    const paddleHeight = 100;
    const paddleSpeed = 10;

    // Player racket
    const player = {
        x: 10,
        y: fieldHeight / 2 - paddleHeight / 2,
        width: paddleWidth,
        height: paddleHeight,
        color: "#FF5733",
        dy: 0,
    };

    // AI racket
    const ai = {
        x: fieldWidth - paddleWidth - 10,
        y: fieldHeight / 2 - paddleHeight / 2,
        width: paddleWidth,
        height: paddleHeight,
        color: "#33FFA8",
        dy: paddleSpeed,
    };

    // Ball
    const ball = {
        x: fieldWidth / 2,
        y: fieldHeight / 2,
        radius: 10,
        speed: 5,
        dx: 5,
        dy: 5,
        color: "#fff",
    };

    // Kaydırıcı değerini dinleyen olay dinleyicisi
    const ballSpeedSlider = document.getElementById('ballSpeedSlider');
    ballSpeedSlider.addEventListener('input', function() {
        const newSpeed = parseInt(this.value);
        updateBallSpeed(newSpeed);
    });

    // Topun hızını güncelleme fonksiyonu
    function updateBallSpeed(newSpeed) {
        ball.speed = newSpeed;
        updateBallDirection();
    }

    // Topun yönünü güncelleme fonksiyonu
    function updateBallDirection() {
      const speedFactor = ball.speed / Math.sqrt(ball.dx * ball.dx + ball.dy * ball.dy);
      ball.dx *= speedFactor;
      ball.dy *= speedFactor;
    }

    // Scores
    let playerScore = 0;
    let aiScore = 0;
    // Check if the game is over
    let gameOver = false;

    // Player and AI scores update
    function updateScore() {
        if (playerScore >= 11 || aiScore >= 11) {
            gameOver = true;
        }
    }

    // Play again
    function playAgain() {
        playerScore = 0;
        aiScore = 0;
        gameOver = false;
    }

    // Game difficulty level
    let difficulty = "medium";

    // Clear the playground
    function clearField() {
        context.fillStyle = "#000";
        context.fillRect(0, 0, fieldWidth, fieldHeight);
    }

    // Draw player and AI rackets
    function drawPaddles() {
        context.fillStyle = player.color;
        context.fillRect(player.x, player.y, player.width, player.height);
        context.fillStyle = ai.color;
        context.fillRect(ai.x, ai.y, ai.width, ai.height);
    }

    // Draw the field lines
    function drawNet() {
        context.fillStyle = "#fff";
        for (let i = 0; i <= canvas.height; i += 15) {
            context.fillRect(canvas.width / 2 - 1, i, 2, 10);
        }
    }

    // Draw the ball
    function drawBall() {
        context.fillStyle = ball.color;
        context.beginPath();
        context.arc(ball.x, ball.y, ball.radius, 0, Math.PI * 2, false);
        context.closePath();
        context.fill();
    }


    // Draw the scores
    function drawScores() {
        context.fillStyle = "#fff";
        context.font = "30px Arial";
        context.fillText(playerScore, fieldWidth / 4, 50);
        context.fillText(aiScore, (3 * fieldWidth) / 4, 50);
        if (playerScore === 11) {
            context.fillText("{% trans 'You Won!' %}", fieldWidth / 2 - 80, 100);
            updateScore();
        } else if (aiScore === 11) {
            context.fillText("{% trans 'You Lost!' %}", fieldWidth / 2 - 80, 100);
            updateScore();
        }
    }

    // Player racket movement
    function movePlayerPaddle() {
        player.y += player.dy;
        if (player.y < 0) {
            player.y = 0;
        } else if (player.y + player.height > fieldHeight) {
            player.y = fieldHeight - player.height;
        }
    }

    // AI racket movement
    function moveAiPaddle() {
        const aiCenter = ai.y + ai.height / 2;
        const ballCenter = ball.y;

        if (difficulty === "easy") {
            // Easy difficulty level: AI paddle moves slowly
            ai.dy = paddleSpeed * 0.09;
        } else if (difficulty === "medium") {
            // Medium difficulty level: AI paddle moves at medium speed
            ai.dy = paddleSpeed * 0.2;
        } else if (difficulty === "hard") {
            // Hard difficulty level: AI racket moves fast
            ai.dy = paddleSpeed * 2;
        }

        // AI racket moving in the direction of the ball
        if (aiCenter < ballCenter - 35) {
            ai.y += ai.dy;
        } else if (aiCenter > ballCenter + 35) {
            ai.y -= ai.dy;
        }

        // AI racket does not leave the player area
        if (ai.y < 0) {
            ai.y = 0;
        } else if (ai.y + ai.height > fieldHeight) {
            ai.y = fieldHeight - ai.height;
        }
    }

    // Ball movement
    function moveBall() {
        ball.x += ball.dx;
        ball.y += ball.dy;

        // Wall impact control
        if (ball.y + ball.radius > fieldHeight || ball.y - ball.radius < 0) {
        	ball.dy *= -1;
        }

        // Player and AI paddle collision control
        if (
            ball.x - ball.radius < player.x + player.width &&
            ball.y + ball.radius > player.y &&
            ball.y - ball.radius < player.y + player.height
        ) {
            ball.dx *= -1;
        } else if (
            ball.x + ball.radius > ai.x &&
            ball.y + ball.radius > ai.y &&
            ball.y - ball.radius < ai.y + ai.height
        ) {
            ball.dx *= -1;
        }

        // Score check
        if (ball.x - ball.radius < 0) {
            aiScore++;
            resetBall();
        } else if (ball.x + ball.radius > fieldWidth) {
            playerScore++;
            resetBall();
        }
    }

    // Bring the ball to the center
    function resetBall() {
        ball.x = fieldWidth / 2;
        ball.y = fieldHeight / 2;
        ball.speed = 5;
        ball.dx *= -1;
        ball.dy *= Math.random() < 0.5 ? -1 : 1;
    }

    // Game Loop
    function gameLoop() {
        if (gameOver)
            setTimeout(function() {
                window.location.href = '{% url "pong:home" %}';
			}, 1000);
        else {
            clearField();
            drawPaddles();
            drawBall();
            drawScores();
            movePlayerPaddle();
            drawNet();
            moveAiPaddle();
            moveBall();
            requestAnimationFrame(gameLoop);
        }
    }

    // Start the Game
    function startGame() {
        playerScore = 0;
        aiScore = 0;
        resetBall();
        gameLoop();
    }

    // Adjust difficulty level
    function setDifficulty(level) {
        difficulty = level;
    }

    // Control the movement of the player paddle
    document.addEventListener("keydown", function (event) {
        if (event.code === "ArrowUp") {
            player.dy = -paddleSpeed;
        } else if (event.code === "ArrowDown") {
            player.dy = paddleSpeed;
        }
    });

    document.addEventListener("keyup", function (event) {
        if (event.code === "ArrowUp" || event.code === "ArrowDown") {
            player.dy = 0;
        }
    });

    function toggleSettingsModal() {
        const modal = document.getElementById('settingsModal');
        const modalBackdrop = document.querySelector('.modal-backdrop');

        if (modal.classList.contains('show')) {
            modal.classList.remove('show');
            modalBackdrop.remove();
        } else {
            modal.classList.add('show');
            document.body.classList.add('modal-open');
            document.body.appendChild(modalBackdrop);
        }
    }

    function applyColor() {
        const playerColor = document.getElementById('playerColorPicker').value;
        const aiColor = document.getElementById('aiColorPicker').value;

        player.color = playerColor;
        ai.color = aiColor;
        // Close the modal after applying settings
        toggleSettingsModal();
    }

    // Start the Game
    startGame();
</script>

srcs/requirements/main/pong/templates/js/oda.html
{{room_name|json_script:"roomName"}}
{% load i18n %}
<script>
	const oda = JSON.parse(document.getElementById("roomName").textContent);
    const s = new WebSocket(`${window.location.protocol === 'https:' ? 'wss' : 'ws'}://${window.location.host}/ws/pong/${oda}`);


	// Oyuncu Ayarı
	var playerCount = 0;
	let p2 = true;
	let user = '{{user}}';
	var p1Socket = '{{ creator }}';
	var p2Socket = '{{ opponent }}';

	// WebSocket bağlantısı açıldığında tetiklenen olay işleyicisi
	s.onopen = function() {
		if (user === p2Socket && p2 && (player1Score === 0 && player2Score === 0)){
			if(player1Score === 0 && player2Score === 0)
				s.send(JSON.stringify(data = {type: 'update', player: 1}));
		}
		if (p1Socket && p2Socket){
			if (p1Socket != '' ){
				playerCount++;
			}
			if (p1Socket !== '' && (p2Socket !== '' || p2Socket !== "None"))
				playerCount++;
			if(p2Socket === "None")
				playerCount--;
			if(playerCount === 2)
			{
				// Oyun döngüsünü başlatır
				gameLoop();
			}
			else{
				context.font = "30px Arial";
				context.fillStyle = "White";
				context.fillText("{% trans 'Player Pending' %}...", canvas.width / 2 - 150, canvas.height / 2);
			}
		}
	};	
	// WebSocket bağlantısı kapandığında tetiklenen olay işleyicisi
	s.onclose = function() {
		gameOver = true;
		sendGameOver();
		setTimeout(function() {
			window.location.href = '{% url "pong:home" %}';
		}, 1500);
	};

	const canvas = document.getElementById("pong");
	const context = canvas.getContext("2d");

	// Raket Ayarları
	const paddleWidth = 10;
	const paddleHeight = 90;
	let player1Y = canvas.height / 2 - paddleHeight / 2;
	let player2Y = canvas.height / 2 - paddleHeight / 2;
	// Raket Rengi
	let paddleColor1 = "#fff";
	let paddleColor2 = "#fff";

	// Top Ayarları
	let ballPosition = {
		x: canvas.width / 2,
		y: canvas.height / 2
	};
	//top Hızı
	let ballSpeed = {
		x: 5,
		y: 5
	};
	//Topun yuvarlıklıgı
	const ballRadius = 7;
	//Topun Rengi
	let ballColor = "#fff";
	//Düğme durumu
	let bas = false;
	// Oyuncu  Puanı
	var player1Score = 0;
	var player2Score = 0;
	const winnerScore = 11;

	// Game State
	var gameOver = false;

	// Topu hareket ettirmek için kullanılan fonksiyon
	function moveBall() {
		// Topun konumunu günceller
		ballPosition.x += ballSpeed.x;
		ballPosition.y += ballSpeed.y;

		// Topun oyun alanının duvarlarına çarpmasını kontrol eder
		if (ballPosition.x < 0 || ballPosition.x > canvas.width) {
			ballSpeed.x = -ballSpeed.x;
		}

		if (ballPosition.y < 0 || ballPosition.y > canvas.height) {
			ballSpeed.y = -ballSpeed.y;
		}

		// Raket çarpışma olup olmadığını kontrol edin
		if (ballPosition.x - ballRadius < paddleWidth && ballPosition.y > player1Y && ballPosition.y < player1Y + paddleHeight) {
			ballSpeed.x = -ballSpeed.x;
		} else if (ballPosition.x  + ballRadius > canvas.width - paddleWidth && ballPosition.y > player2Y && ballPosition.y < player2Y + paddleHeight) {
			ballSpeed.x = -ballSpeed.x;
		}
	}

	function scorecont(){
		sendPlayerScore(1,player1Score);
		sendPlayerScore(2,player2Score);
	}

	function colorcont(){
		sendPlayerColor(1,paddleColor1);
		sendPlayerColor(2,paddleColor2);
	}

	function puankont(){
		if (p1Socket === user){
		if (ballPosition.x - ballRadius < 0) {
			player2Score++;	
			document.getElementById("player2-score").textContent = player2Score;
			scorecont();
			resetBall();
		} else if (ballPosition.x + ballRadius > canvas.width) {
			player1Score++;
			document.getElementById("player1-score").textContent = player1Score;
			scorecont();
			resetBall();
		}
		}
		if (document.getElementById("player1-score").textContent)
            document.getElementById("player1-score").textContent = player1Score;
		if (document.getElementById("player2-score").textContent)
            document.getElementById("player2-score").textContent = player2Score;

	}

	// WebSocket bağlantısı üzerinden mesaj alındığında tetiklenen olay işleyicisi
	s.onmessage = function(event) {
		const data = JSON.parse(event.data);
		// Mesajın türüne göre işlem yap
		switch (data.type) {
			case 'update':
				if (data.player === 1 && p2){
					if (user === p1Socket && p2)
						location.reload();
					p2 = false;
				}
				break;
			
			case 'paddlePosition':
				// Diğer oyuncunun sopasının konumunu güncelle
				if (data.player === 1) {
					player1Y = data.position;
				} else if (data.player === 2) {
					player2Y = data.position;
				}
				break;

			case 'ballPosition':
				// Topun konumunu güncelle
				if (p2Socket === user){
					ballPosition = data.position;
				}
					//ballPosition = data.position;
				break;

			case 'playerScore':
				// Oyuncu skorunu güncelle
				if (data.player === 1) {
					player1Score = data.score;
				} else if (data.player === 2) {
					player2Score = data.score;
				}
				break;

			case 'colorAll':
				// renk
				if (data.player === 1) {
					paddleColor1 = data.color;
				} else if (data.player === 2) {
					paddleColor2 = data.color;
				}
				break;

			case 'gameOver':
				// Oyunu bitir
				gameOver = true;
				if(player1Score > player2Score){
					winner = p1Socket}
				else{
					winner = p2Socket}
				sendWinnerToServer(winner)
				break;
		}
	};

	async function sendWinnerToServer(winner) {
		if (winner) {
			const url = "{% url 'pong:update' room_name %}"
			await fetch(url, {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'X-CSRFToken': '{{ csrf_token }}',
				},
				body: JSON.stringify({
					'winner': winner,
				}),
			})
			.then(response => response.json())
			.then(data => {
				if (data.success) {
					// updated
				} else {
					console.error("{% trans 'Failed to update winner:' %}", data.error);
				}
			})
			.catch(error => console.error("{% trans 'Error updating winner:' %}", error));
		}
	}

	// Oyuncu 1'in sopasının konumunu diğer oyuncuya göndermek için kullanılan fonksiyon
	function sendPlayer1PaddlePosition() {
		if (s.readyState === WebSocket.OPEN) {
			const data = {
				type: 'paddlePosition',
				player: 1,
				position: player1Y
			};
			if(user === p1Socket)
				s.send(JSON.stringify(data));}	
		}
	
	// Oyuncu 2'nin sopasının konumunu diğer oyuncuya göndermek için kullanılan fonksiyon
	function sendPlayer2PaddlePosition() {
	if (s.readyState === WebSocket.OPEN) {
		const data = {
			type: 'paddlePosition',
			player: 2,
			position: player2Y
		};
		if(user === p2Socket)
			s.send(JSON.stringify(data));}
	}
	
	// Topun konumunu diğer oyuncuya göndermek için kullanılan fonksiyon
	function sendBallPosition() {
	if (s.readyState === WebSocket.OPEN && p1Socket === user) {
		const data = {
			type: 'ballPosition',
			position: ballPosition
		};
		s.send(JSON.stringify(data));
		}
	}
	
	// Oyuncu skorunu diğer oyuncuya göndermek için kullanılan fonksiyon
	function sendPlayerScore(player, score) {
	if (s.readyState === WebSocket.OPEN) {
		const data = {
			type: 'playerScore',
			player: player,
			score: score
		};
		s.send(JSON.stringify(data));
		}
	}
	// Oyuncu raket rengini diğer oyuncuya göndermek için kullanılan fonksiyon
	function sendPlayerColor(player, color) {
		if (s.readyState === WebSocket.OPEN) {
			const data = {
				type: 'colorAll',
				player: player,
				color: color
			};
			s.send(JSON.stringify(data));
			}
		}
	
	// Oyunun bittiğini diğer oyuncuya göndermek için kullanılan fonksiyon
	function sendGameOver() {
	if (s.readyState === WebSocket.OPEN) {
		const data = {
			type: 'gameOver',
		};
		s.send(JSON.stringify(data));
		}
	}

	// document.addEventListener("keydown", function(event) {
	// 	if (!bas) {
	// 		bas = true;
	// 		updatePaddleAndScore(event);
	// 	}
	// 	updatePaddleAndScore(event);
	// });
	
	document.addEventListener("keyup", function(event) {
		updatePaddleAndScore(event);
	});
	function resetBall() {
		ballPosition.x = canvas.width / 2;
		ballPosition.y = (canvas.height / 2 ) * Math.random();
		ballSpeed.x = -ballSpeed.x;
		ballSpeed.y = 5;
	}
	// Raketleri çizer
	function drawPaddles() {
		context.fillStyle = paddleColor1;
		context.fillRect(10, player1Y, paddleWidth, paddleHeight);
		context.fillStyle = paddleColor2;
		context.fillRect(canvas.width - paddleWidth - 10, player2Y, paddleWidth, paddleHeight);
	}

	// Topu çizer
	function drawBall() {
		context.fillStyle = ballColor;
		context.beginPath();
		context.arc(ballPosition.x, ballPosition.y, ballRadius, 0, Math.PI * 2, false);
		context.closePath();
		context.fill();
	}

	function file(){
		context.fillStyle = "#fff";
		context.fillRect(canvas.width / 2 - 2, 0, 4, canvas.height);
	}

	function updatePaddleAndScore(event){
		if(p1Socket == user){
			if (event.key === "w" && player1Y > 0) {
				player1Y -= 30;
				sendPlayer1PaddlePosition();
			}
			if (event.key === "s" && player1Y < canvas.height - paddleHeight) {
				player1Y += 30;
				sendPlayer1PaddlePosition();
			}
		}else{
			if (event.key === "ArrowUp" && player2Y > 0) {
				player2Y -= 30;
				sendPlayer2PaddlePosition();
			}
			if (event.key === "ArrowDown" && player2Y < canvas.height - paddleHeight) {
				player2Y += 30;
				sendPlayer2PaddlePosition();
			}
		}


		//Puan Kontrol
		if (player1Score === winnerScore || player2Score === winnerScore) {
			// Puan Kontrolü
			document.getElementById("player1-score").textContent = player1Score;
			document.getElementById("player2-score").textContent = player2Score;
			gameOver = true;	
			sendGameOver();
			setTimeout(function() {
				window.location.href = '{% url "pong:home" %}';
				}, 3000);
		}
	}


	function updatePaddleAndScor(){
		//Puan Kontrol
		if (player1Score === winnerScore || player2Score === winnerScore) {
			// Puan Kontrolü
			document.getElementById("player1-score").textContent = player1Score;
			document.getElementById("player2-score").textContent = player2Score;
			gameOver = true;	
			sendGameOver();
			setTimeout(function() {
				window.location.href = '{% url "pong:home" %}';
				}, 3000);
		}
	}

	let lastUpdateTime = 0;
	const updateInterval = 15;
	// Oyun döngüsü
	function gameLoop(timestamp) {
		if (timestamp - lastUpdateTime > updateInterval) {
			moveBall();
			sendBallPosition();
			lastUpdateTime = timestamp;
		}
		// Canvas'ı temizler
		context.clearRect(0, 0, canvas.width, canvas.height);
		if (gameOver) {
			context.clearRect(0, 0, canvas.width, canvas.height);
			context.font = "30px Arial";
			context.fillStyle = "White";
			if (winnerScore === player1Score){
				if (p1Socket === user)
					context.fillText("{% trans 'You Won!' %}", canvas.width / 2 - 80, canvas.height / 2);
				else
					context.fillText("{% trans 'You Lost!' %}!", canvas.width / 2 - 80, canvas.height / 2);
			}
			else{
				if (p2Socket === user)
					context.fillText("{% trans 'You Won!' %}", canvas.width / 2 - 80, canvas.height / 2);
				else
					context.fillText("{% trans 'You Lost!' %}!", canvas.width / 2 - 80, canvas.height / 2);
			}
			setTimeout(function() {
				window.location.href = '{% url "pong:home" %}';
			}, 3000);
		}
		else {
			// Raketleri çizer
			drawPaddles();
			// Topu çizer
			drawBall();
			//Raket Hareketi
			updatePaddleAndScor();
			//Puan Kontrol
			puankont();
			// File çizer
			file();
			//Top hareketi
			//if(p1Socket === user)
				//moveBall();
			// Oyun döngüsünü tekrar başlatır
			requestAnimationFrame(gameLoop);
		}
	}

	function getRandomColor() {
		var rasgele = '0123456789ABCDEF';
		var color = '#';
		for (var i = 0; i < 6; i++) {
		  color += rasgele[Math.floor(Math.random() * 16)];
		}
		return color;
	}
  
	function changeColor(elementId) {
		var color = getRandomColor();

		if (elementId === 'paddleColor1') {
			paddleColor1 = color;
		} else if (elementId === 'paddleColor2') {
			paddleColor2 = color;
		} else if (elementId === 'ballColor') {
			ballColor = color;
		}
		colorcont();
	}

	window.addEventListener('DOMContentLoaded', function() {
		preventWindowResize();
	  });
	  
	  window.addEventListener('resize', function() {
		preventWindowResize();
	  });
	  
	  function preventWindowResize() {
		var windowWidth = window.innerWidth;
		var windowHeight = window.innerHeight;
	  
		if (windowWidth < 1024 || windowHeight < 800) {
		  window.resizeTo(1024, 800);
		}
	  }

	// Top Hareketi
	//setInterval(sendBallPosition, 1);
</script>